**WHAT IS NUMPY ?**

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types, with many operations being performed in compiled code for performance. There are several important differences between NumPy arrays and the standard Python sequences:

NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory. The exception: one can have arrays of (Python, including NumPy) objects, thereby allowing for arrays of different sized elements.

NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays. In other words, in order to efficiently use much (perhaps even most) of today’s scientific/mathematical Python-based software, just knowing how to use Python’s built-in sequence types is insufficient - one also needs to know how to use NumPy arrays.

The points about sequence size and speed are particularly important in scientific computing. As a simple example, consider the case of multiplying each element in a 1-D sequence with the corresponding element in another sequence of the same length. If the data are stored in two Python lists, a and b, we could iterate over each element:

***NumPy gives us the best of both worlds:*** element-by-element operations are the “default mode” when an ndarray is involved, but the element-by-element operation is speedily executed by pre-compiled C code. In NumPy

$$
c = a * b
$$
does what the earlier examples do, at near-C speeds, but with the code simplicity we expect from something based on Python. Indeed, the NumPy idiom is even simpler! This last example illustrates two of NumPy’s features which are the basis of much of its power: vectorization and broadcasting.

![NumPy Uses](./Uses-of-NumPy-1.webp)

![Numerical Computing with Python and NumPy](./mg8O3kd.png)

**# Why is NumPy Fast?**

Vectorization describes the absence of any explicit looping, indexing, etc., in the code - these things are taking place, of course, just “behind the scenes” in optimized, pre-compiled C code. Vectorized code has many advantages, among which are:

vectorized code is more concise and easier to read

fewer lines of code generally means fewer bugs

the code more closely resembles standard mathematical notation (making it easier, typically, to correctly code mathematical constructs)

vectorization results in more “Pythonic” code. Without vectorization, our code would be littered with inefficient and difficult to read for loops.

Broadcasting is the term used to describe the implicit element-by-element behavior of operations; generally speaking, in NumPy all operations, not just arithmetic operations, but logical, bit-wise, functional, etc., behave in this implicit element-by-element fashion, i.e., they broadcast. Moreover, in the example above, a and b could be multidimensional arrays of the same shape, or a scalar and an array, or even two arrays of with different shapes, provided that the smaller array is “expandable” to the shape of the larger in such a way that the resulting broadcast is unambiguous. For detailed “rules” of broadcasting see Broadcasting.

**# Who Else Uses NumPy?**
NumPy fully supports an object-oriented approach, starting, once again, with ndarray. For example, ndarray is a class, possessing numerous methods and attributes. Many of its methods are mirrored by functions in the outer-most NumPy namespace, allowing the programmer to code in whichever paradigm they prefer. This flexibility has allowed the NumPy array dialect and NumPy ndarray class to become the de-facto language of multi-dimensional data interchange used in Python.

**# Basics of NumPy:** 

NumPy’s main object is the homogeneous multidimensional array. It is a table of elements (usually numbers), all of the same type, indexed by a tuple of non-negative integers. In NumPy dimensions are called axes.

For example, the array for the coordinates of a point in 3D space, [1, 2, 1], has one axis. That axis has 3 elements in it, so we say it has a length of 3. In the example pictured below, the array has 2 axes. The first axis has a length of 2, the second axis has a length of 3.

$$
[[1., 0., 0.],
 [0., 1., 2.]]
$$
NumPy’s array class is called ndarray. It is also known by the alias array. Note that numpy.array is not the same as the Standard Python Library class array.array, which only handles one-dimensional arrays and offers less functionality. The more important attributes of an ndarray object are:

**ndarray.ndim**
the number of axes (dimensions) of the array.

**ndarray.shape**
the dimensions of the array. This is a tuple of integers indicating the size of the array in each dimension. For a matrix with n rows and m columns, shape will be (n,m). The length of the shape tuple is therefore the number of axes, ndim.

**ndarray.size**
the total number of elements of the array. This is equal to the product of the elements of shape.

**ndarray.dtype**
an object describing the type of the elements in the array. One can create or specify dtype’s using standard Python types. Additionally NumPy provides types of its own. numpy.int32, numpy.int16, and numpy.float64 are some examples.

**ndarray.itemsize**
the size in bytes of each element of the array. For example, an array of elements of type float64 has itemsize 8 (=64/8), while one of type complex32 has itemsize 4 (=32/8). It is equivalent to ndarray.dtype.itemsize.

**ndarray.data**
the buffer containing the actual elements of the array. Normally, we won’t need to use this attribute because we will access the elements in an array using indexing facilities.

In [5]:
import numpy as np

arr_example_1 = np.array([1, 2, 3, 4, 5]) #One Dimension

print(arr_example_1)

print(type(arr_example_1))





[1 2 3 4 5]
<class 'numpy.ndarray'>


In [6]:
arr_example_1.itemsize

4

In [7]:
arr_example_1.dtype.name

'int32'

In [8]:
arr_example_1.ndim

1

In [5]:
arr_example_1.shape

(5,)

In [9]:
arr_example_2 = np.arange(12).reshape(3, 4) 
print(arr_example_2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [10]:
arr_example_2.shape


(3, 4)

In [11]:
arr_example_2.ndim

2

In [9]:
arr_example_2.dtype.name

'int32'

In [ ]:

print(np.__version__)

1.21.5


**Array Creation**

you can create an array from a regular Python list or tuple using the array function. The type of the resulting array is deduced from the type of the elements in the sequences.


In [11]:
arr_example_3 = np.array([2,3,4])
arr_example_4 = np.array([2.75, 3.55, 4.89])
arr_example_5 = np.array([(7,8), (9, 10)], dtype=complex)

In [12]:
arr_example_3.dtype

dtype('int32')

In [13]:
arr_example_4.dtype

dtype('float64')

In [14]:
print(arr_example_5)

[[ 7.+0.j  8.+0.j]
 [ 9.+0.j 10.+0.j]]


The function zeros creates an array full of zeros and the function ones creates an array full of ones and the function empty
creates and array whose initial content is random and depends on the state of the memory . by default the datatype 
of created array is float 64.


In [13]:
np.zeros((3, 4))


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [19]:
np.empty((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

 **# What’s the difference between a Python list and a NumPy array?**
 NumPygives you an enormous range of fast and efficient ways of creating arrays and manipulating numerical data inside  them. While a Python list can contain different data types within a single list, all of the elements in a NumPy array should  be homogeneous. The mathematical operations that are meant to be performed on arrays would be extremely inefficient  if the arrays weren’t homogeneous.
 
 **# Why use NumPy?**
 NumPy arrays are faster and more compact than Python lists. An array consumes less memory and is convenient to use.  NumPy uses much less memory to store data and it provides a mechanism of specifying the data types. This allows the  code to be optimized even further

In [25]:
a = np.array([1,2,3,4,5])
b = np.array([[5, 4, 3, 2], [9,8,6,7]])
print(a[0])
print(b[1])

1
[9 8 6 7]


You might occasionally hear an array referred to as a “ndarray,” which is shorthand for “N-dimensional array.” An N dimensional array is simply an array with any number of dimensions. You might also hear 1-D, or one-dimensional array,  2-D, or two-dimensional array, and so on. The NumPy ndarray class is used to represent both matrices and vectors. A  vector is an array with a single dimension (there’s no difference between row and column vectors), while a matrix refers  to an array with two dimensions. For 3-D or higher dimensional arrays, the term tensor is also commonly used.

 **What are the attributes of an array?**
 
 An array is usually a fixed-size container of items of the same type and size. The number of dimensions and items in  an array is defined by its shape. The shape of an array is a tuple of non-negative integers that specify the sizes of each  dimension.

You can also use np.linspace() to create an array with values that are spaced linearly in a specified interval

In [26]:
np.linspace(0, 10 , num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

 **Adding, removing, and sorting elements**

In [27]:
arr_example_2 = np.array([2, 9, 4, 1, 8, 3, 6 , 7])
np.sort(arr_example_2)

array([1, 2, 3, 4, 6, 7, 8, 9])

In [28]:
# you can concatenate arrays aswell
import numpy as np
x = np.array([1, 2, 3]) 
y = np.array([4, 5, 6])
print(np.concatenate([x, y]))

[1 2 3 4 5 6]


**Can you reshape an array ?**

 Yes!,  Using arr.reshape() will give a new shape to an array without changing the data. Just remember that when you use  the reshape method, the array you want to produce needs to have the same number of elements as the original array. If you start with an array with 12 elements, you’ll need to make sure that your new array also has a total of 12 elements


In [34]:
a = np.arange(15)
b = a.reshape(3,5)
c = a.reshape(5, 3)
print(b)
print(c)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [37]:
#You can use np.newaxis to add a new axis:
a2 = a[np.newaxis, :]
a2.shape

(1, 15)

In [41]:
#  Indexing and slicing

a3 = np.array ([[12, 24 , 36], [10 , 20 , 30 ], [11, 22, 33]])

a3[-2:]

array([[10, 20, 30],
       [11, 22, 33]])

In [42]:
a3[0:2]


array([[12, 24, 36],
       [10, 20, 30]])